apiVersion: v1
kind: Pod 
metadata:
  name: my-app
  labels:
    tier: front 
  annotations:
    version: '3.2'
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
          name: nginx-port
      resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeSelector:
    size: medium    # Labels assigned to the Node by "kubectl label nodes node-name size=medium"