apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: web
spec:
  containers:
  - name: webapp
    image: apache2
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"   # OR 0.1
      limits:
        memory: "200Mi"
        cpu: "300m"   # OR 0.3
    ports:
      - containerPort: 80

# here on cpu "100m" means 100 Millicores    and memory "100Mi" means 100 Mebibytes
# 1 Core CPU = 1000m (Milicores)      1Gi (GibiByte) RAM = 1024Mi (Mebibytes)


# By Default Kubernetes sets limits of "1 vCPU" of cpu and "512Mi" of memory for each pods