---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: my-container
    image: nginx:latest
    ports:
    - containerPort: 80
      name: nginx-port
    env:
    - name: ENV_VARIABLE
      value: "value"
    volumeMounts:
    - name: my-volume
      mountPath: /data
  volumes:
  - name: my-volume
    emptyDir: {}