apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    type: rc 
spec:
  replicas: 3
  selector:
    tier: backend
  template:
    metadata:
      name: myapp
      labels:
        tier: backend
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
